export const CountryCodes = [
    { value: "0093", label: "Afghanistan (+93)" },
    { value: "00355", label: "Albania (+355)" },
    { value: "00213", label: "Algeria (+213)" },
    { value: "001-684", label: "American Samoa (+1-684)" },
    { value: "00376", label: "Andorra (+376)" },
    { value: "00244", label: "Angola (+244)" },
    { value: "001-264", label: "Anguilla (+1-264)" },
    { value: "00672", label: "Antarctica (+672)" },
    { value: "001-268", label: "Antigua and Barbuda (+1-268)" },
    { value: "0054", label: "Argentina (+54)" },
    { value: "00374", label: "Armenia (+374)" },
    { value: "00297", label: "Aruba (+297)" },
    { value: "0061", label: "Australia (+61)" },
    { value: "0043", label: "Austria (+43)" },
    { value: "00994", label: "Azerbaijan (+994)" },
    { value: "001-242", label: "Bahamas (+1-242)" },
    { value: "00973", label: "Bahrain (+973)" },
    { value: "00880", label: "Bangladesh (+880)" },
    { value: "001-246", label: "Barbados (+1-246)" },
    { value: "00375", label: "Belarus (+375)" },
    { value: "0032", label: "Belgium (+32)" },
    { value: "00501", label: "Belize (+501)" },
    { value: "00229", label: "Benin (+229)" },
    { value: "001-441", label: "Bermuda (+1-441)" },
    { value: "00975", label: "Bhutan (+975)" },
    { value: "00591", label: "Bolivia (+591)" },
    { value: "00387", label: "Bosnia and Herzegovina (+387)" },
    { value: "00267", label: "Botswana (+267)" },
    { value: "0055", label: "Brazil (+55)" },
    { value: "00246", label: "British Indian Ocean Territory (+246)" },
    { value: "001-284", label: "British Virgin Islands (+1-284)" },
    { value: "00673", label: "Brunei (+673)" },
    { value: "00359", label: "Bulgaria (+359)" },
    { value: "00226", label: "Burkina Faso (+226)" },
    { value: "00257", label: "Burundi (+257)" },
    { value: "00855", label: "Cambodia (+855)" },
    { value: "00237", label: "Cameroon (+237)" },
    { value: "001", label: "Canada (+1)" },
    { value: "00238", label: "Cape Verde (+238)" },
    { value: "001-345", label: "Cayman Islands (+1-345)" },
    { value: "00236", label: "Central African Republic (+236)" },
    { value: "00235", label: "Chad (+235)" },
    { value: "0056", label: "Chile (+56)" },
    { value: "0086", label: "China (+86)" },
    { value: "0061", label: "Christmas Island (+61)" },
    { value: "0061", label: "Cocos Islands (+61)" },
    { value: "0057", label: "Colombia (+57)" },
    { value: "00269", label: "Comoros (+269)" },
    { value: "00682", label: "Cook Islands (+682)" },
    { value: "00506", label: "Costa Rica (+506)" },
    { value: "00385", label: "Croatia (+385)" },
    { value: "0053", label: "Cuba (+53)" },
    { value: "00599", label: "Curacao (+599)" },
    { value: "00357", label: "Cyprus (+357)" },
    { value: "00420", label: "Czech Republic (+420)" },
    { value: "00243", label: "Democratic Republic of the Congo (+243)" },
    { value: "0045", label: "Denmark (+45)" },
    { value: "00253", label: "Djibouti (+253)" },
    { value: "001-767", label: "Dominica (+1-767)" },
    { value: "001-809, 1-829, 1-849", label: "Dominican Republic (+1-809, 1-829, 1-849)" },
    { value: "00670", label: "East Timor (+670)" },
    { value: "00593", label: "Ecuador (+593)" },
    { value: "0020", label: "Egypt (+20)" },
    { value: "00503", label: "El Salvador (+503)" },
    { value: "00240", label: "Equatorial Guinea (+240)" },
    { value: "00291", label: "Eritrea (+291)" },
    { value: "00372", label: "Estonia (+372)" },
    { value: "00251", label: "Ethiopia (+251)" },
    { value: "00500", label: "Falkland Islands (+500)" },
    { value: "00298", label: "Faroe Islands (+298)" },
    { value: "00679", label: "Fiji (+679)" },
    { value: "00358", label: "Finland (+358)" },
    { value: "0033", label: "France (+33)" },
    { value: "00689", label: "French Polynesia (+689)" },
    { value: "00241", label: "Gabon (+241)" },
    { value: "00220", label: "Gambia (+220)" },
    { value: "00995", label: "Georgia (+995)" },
    { value: "0049", label: "Germany (+49)" },
    { value: "00233", label: "Ghana (+233)" },
    { value: "00350", label: "Gibraltar (+350)" },
    { value: "0030", label: "Greece (+30)" },
    { value: "00299", label: "Greenland (+299)" },
    { value: "001-473", label: "Grenada (+1-473)" },
    { value: "001-671", label: "Guam (+1-671)" },
    { value: "00502", label: "Guatemala (+502)" },
    { value: "0044-1481", label: "Guernsey (+44-1481)" },
    { value: "00224", label: "Guinea (+224)" },
    { value: "00245", label: "Guinea-Bissau (+245)" },
    { value: "00592", label: "Guyana (+592)" },
    { value: "00509", label: "Haiti (+509)" },
    { value: "00504", label: "Honduras (+504)" },
    { value: "00852", label: "Hong Kong (+852)" },
    { value: "0036", label: "Hungary (+36)" },
    { value: "00354", label: "Iceland (+354)" },
    { value: "0091", label: "India (+91)" },
    { value: "0062", label: "Indonesia (+62)" },
    { value: "0098", label: "Iran (+98)" },
    { value: "00964", label: "Iraq (+964)" },
    { value: "00353", label: "Ireland (+353)" },
    { value: "0039", label: "Italy (+39)" },
    { value: "00225", label: "Ivory Coast (+225)" },
    { value: "001-876", label: "Jamaica (+1-876)" },
    { value: "0081", label: "Japan (+81)" },
    { value: "0044-1534", label: "Jersey (+44-1534)" },
    { value: "00962", label: "Jordan (+962)" },
    { value: "007", label: "Kazakhstan (+7)" },
    { value: "00254", label: "Kenya (+254)" },
    { value: "00686", label: "Kiribati (+686)" },
    { value: "00383", label: "Kosovo (+383)" },
    { value: "00965", label: "Kuwait (+965)" },
    { value: "00996", label: "Kyrgyzstan (+996)" },
    { value: "00856", label: "Laos (+856)" },
    { value: "00371", label: "Latvia (+371)" },
    { value: "00961", label: "Lebanon (+961)" },
    { value: "00266", label: "Lesotho (+266)" },
    { value: "00231", label: "Liberia (+231)" },
    { value: "00218", label: "Libya (+218)" },
    { value: "00423", label: "Liechtenstein (+423)" },
    { value: "00370", label: "Lithuania (+370)" },
    { value: "00352", label: "Luxembourg (+352)" },
    { value: "00853", label: "Macau (+853)" },
    { value: "00389", label: "Macedonia (+389)" },
    { value: "00261", label: "Madagascar (+261)" },
    { value: "00265", label: "Malawi (+265)" },
    { value: "0060", label: "Malaysia (+60)" },
    { value: "00960", label: "Maldives (+960)" },
    { value: "00223", label: "Mali (+223)" },
    { value: "00356", label: "Malta (+356)" },
    { value: "00692", label: "Marshall Islands (+692)" },
    { value: "00222", label: "Mauritania (+222)" },
    { value: "00230", label: "Mauritius (+230)" },
    { value: "00262", label: "Mayotte (+262)" },
    { value: "0052", label: "Mexico (+52)" },
    { value: "00691", label: "Micronesia (+691)" },
    { value: "00373", label: "Moldova (+373)" },
    { value: "00377", label: "Monaco (+377)" },
    { value: "00976", label: "Mongolia (+976)" },
    { value: "00382", label: "Montenegro (+382)" },
    { value: "001-664", label: "Montserrat (+1-664)" },
    { value: "00212", label: "Morocco (+212)" },
    { value: "00258", label: "Mozambique (+258)" },
    { value: "0095", label: "Myanmar (+95)" },
    { value: "00264", label: "Namibia (+264)" },
    { value: "00674", label: "Nauru (+674)" },
    { value: "00977", label: "Nepal (+977)" },
    { value: "0031", label: "Netherlands (+31)" },
    { value: "00599", label: "Netherlands Antilles (+599)" },
    { value: "00687", label: "New Caledonia (+687)" },
    { value: "0064", label: "New Zealand (+64)" },
    { value: "00505", label: "Nicaragua (+505)" },
    { value: "00227", label: "Niger (+227)" },
    { value: "00234", label: "Nigeria (+234)" },
    { value: "00683", label: "Niue (+683)" },
    { value: "00850", label: "North Korea (+850)" },
    { value: "001-670", label: "Northern Mariana Islands (+1-670)" },
    { value: "0047", label: "Norway (+47)" },
    { value: "00968", label: "Oman (+968)" },
    { value: "0092", label: "Pakistan (+92)" },
    { value: "00680", label: "Palau (+680)" },
    { value: "00970", label: "Palestine (+970)" },
    { value: "00507", label: "Panama (+507)" },
    { value: "00675", label: "Papua New Guinea (+675)" },
    { value: "00595", label: "Paraguay (+595)" },
    { value: "0051", label: "Peru (+51)" },
    { value: "0063", label: "Philippines (+63)" },
    { value: "0064", label: "Pitcairn (+64)" },
    { value: "0048", label: "Poland (+48)" },
    { value: "00351", label: "Portugal (+351)" },
    { value: "001-787,1-939", label: "Puerto Rico (+1-787,1-939)" },
    { value: "00974", label: "Qatar (+974)" },
    { value: "00242", label: "Republic of the Congo (+242)" },
    { value: "00262", label: "Reunion (+262)" },
    { value: "0040", label: "Romania (+40)" },
    { value: "007", label: "Russia (+7)" },
    { value: "00250", label: "Rwanda (+250)" },
    { value: "00590", label: "Saint Barthelemy (+590)" },
    { value: "00290", label: "Saint Helena (+290)" },
    { value: "001-869", label: "Saint Kitts and Nevis (+1-869)" },
    { value: "001-758", label: "Saint Lucia (+1-758)" },
    { value: "00590", label: "Saint Martin (+590)" },
    { value: "00508", label: "Saint Pierre and Miquelon (+508)" },
    { value: "001-784", label: "Saint Vincent and the Grenadines (+1-784)" },
    { value: "00685", label: "Samoa (+685)" },
    { value: "00378", label: "San Marino (+378)" },
    { value: "00966", label: "Saudi Arabia (+966)" },
    { value: "00221", label: "Senegal (+221)" },
    { value: "00381", label: "Serbia (+381)" },
    { value: "00248", label: "Seychelles (+248)" },
    { value: "00232", label: "Sierra Leone (+232)" },
    { value: "0065", label: "Singapore (+65)" },
    { value: "001-721", label: "Sint Maarten (+1-721)" },
    { value: "00421", label: "Slovakia (+421)" },
    { value: "00386", label: "Slovenia (+386)" },
    { value: "00677", label: "Solomon Islands (+677)" },
    { value: "00252", label: "Somalia (+252)" },
    { value: "0027", label: "South Africa (+27)" },
    { value: "0082", label: "South Korea (+82)" },
    { value: "00211", label: "South Sudan (+211)" },
    { value: "0034", label: "Spain (+34)" },
    { value: "0094", label: "Sri Lanka (+94)" },
    { value: "00249", label: "Sudan (+249)" },
    { value: "00597", label: "Suriname (+597)" },
    { value: "00268", label: "Swaziland (+268)" },
    { value: "0046", label: "Sweden (+46)" },
    { value: "0041", label: "Switzerland (+41)" },
    { value: "00963", label: "Syria (+963)" },
    { value: "00886", label: "Taiwan (+886)" },
    { value: "00992", label: "Tajikistan (+992)" },
    { value: "00255", label: "Tanzania (+255)" },
    { value: "0066", label: "Thailand (+66)" },
    { value: "00228", label: "Togo (+228)" },
    { value: "00690", label: "Tokelau (+690)" },
    { value: "00676", label: "Tonga (+676)" },
    { value: "001-868", label: "Trinidad and Tobago (+1-868)" },
    { value: "00216", label: "Tunisia (+216)" },
    { value: "0090", label: "Turkey (+90)" },
    { value: "00993", label: "Turkmenistan (+993)" },
    { value: "001-649", label: "Turks and Caicos Islands (+1-649)" },
    { value: "00688", label: "Tuvalu (+688)" },
    { value: "001-340", label: "US Virgin Islands (+1-340)" },
    { value: "00256", label: "Uganda (+256)" },
    { value: "00380", label: "Ukraine (+380)" },
    { value: "00971", label: "United Arab Emirates (+971)" },
    { value: "0044", label: "United Kingdom (+44)" },
    { value: "001", label: "United States (+1)" },
    { value: "00598", label: "Uruguay (+598)" },
    { value: "00998", label: "Uzbekistan (+998)" },
    { value: "00678", label: "Vanuatu (+678)" },
    { value: "00379", label: "Vatican (+379)" },
    { value: "0058", label: "Venezuela (+58)" },
    { value: "0084", label: "Vietnam (+84)" },
    { value: "00681", label: "Wallis and Futuna (+681)" },
    { value: "00212", label: "Western Sahara (+212)" },
    { value: "00967", label: "Yemen (+967)" },
    { value: "00260", label: "Zambia (+260)" },
    { value: "00263", label: "Zimbabwe (+263)" },
    { value: "0044-1624", label: "isle of man (+44-1624)" },
    { value: "00239", label: "sao tome and principe (+239)" }
].sort((a, b) => {
    let x = a.label.toLowerCase();
    let y = b.label.toLowerCase();
    if (x < y) {
        return -1;
    }
    if (x > y) {
        return 1;
    }
    return 0;
});

export const Countries=[
    {value:"AF",label:"Afghanistan"},
    {value:"AX",label:"land Islands"},
    {value:"AL",label:"Albania"},
    {value:"DZ",label:"Algeria"},
    {value:"AS",label:"American Samoa"},
    {value:"AD",label:"Andorra"},
    {value:"AO",label:"Angola"},
    {value:"AI",label:"Anguilla"},
    {value:"AQ",label:"Antarctica"},
    {value:"AG",label:"Antigua and Barbuda"},
    {value:"AR",label:"Argentina"},
    {value:"AM",label:"Armenia"},
    {value:"AW",label:"Aruba"},
    {value:"AU",label:"Australia"},
    {value:"AT",label:"Austria"},
    {value:"AZ",label:"Azerbaijan"},
    {value:"BS",label:"Bahamas"},
    {value:"BH",label:"Bahrain"},
    {value:"BD",label:"Bangladesh"},
    {value:"BB",label:"Barbados"},
    {value:"BY",label:"Belarus"},
    {value:"BE",label:"Belgium"},
    {value:"BZ",label:"Belize"},
    {value:"BJ",label:"Benin"},
    {value:"BM",label:"Bermuda"},
    {value:"BT",label:"Bhutan"},
    {value:"BO",label:"Bolivia (Plurinational State of)"},
    {value:"BQ",label:"Bonaire, Sint Eustatius and Saba"},
    {value:"BA",label:"Bosnia and Herzegovina"},
    {value:"BW",label:"Botswana"},
    {value:"BV",label:"Bouvet Island"},
    {value:"BR",label:"Brazil"},
    {value:"IO",label:"British Indian Ocean Territory"},
    {value:"BN",label:"Brunei Darussalam"},
    {value:"BG",label:"Bulgaria"},
    {value:"BF",label:"Burkina Faso"},
    {value:"BI",label:"Burundi"},
    {value:"CV",label:"Cabo Verde"},
    {value:"KH",label:"Cambodia"},
    {value:"CM",label:"Cameroon"},
    {value:"CA",label:"Canada"},
    {value:"KY",label:"Cayman Islands"},
    {value:"CF",label:"Central African Republic"},
    {value:"TD",label:"Chad"},
    {value:"CL",label:"Chile"},
    {value:"CN",label:"China"},
    {value:"CX",label:"Christmas Island"},
    {value:"CC",label:"Cocos (Keeling) Islands"},
    {value:"CO",label:"Colombia"},
    {value:"KM",label:"Comoros"},
    {value:"CG",label:"Congo"},
    {value:"CD",label:"Congo (Democratic Republic of the)"},
    {value:"CK",label:"Cook Islands"},
    {value:"CR",label:"Costa Rica"},
    {value:"CI",label:"Cote d'Ivoire"},
    {value:"HR",label:"Croatia"},
    {value:"CU",label:"Cuba"},
    {value:"CW",label:"Curacao"},
    {value:"CY",label:"Cyprus"},
    {value:"CZ",label:"Czech Republic"},
    {value:"DK",label:"Denmark"},
    {value:"DJ",label:"Djibouti"},
    {value:"DM",label:"Dominica"},
    {value:"DO",label:"Dominican Republic"},
    {value:"EC",label:"Ecuador"},
    {value:"EG",label:"Egypt"},
    {value:"SV",label:"El Salvador"},
    {value:"GQ",label:"Equatorial Guinea"},
    {value:"ER",label:"Eritrea"},
    {value:"EE",label:"Estonia"},
    {value:"ET",label:"Ethiopia"},
    {value:"FK",label:"Falkland Islands (Malvinas)"},
    {value:"FO",label:"Faroe Islands"},
    {value:"FJ",label:"Fiji"},
    {value:"FI",label:"Finland"},
    {value:"FR",label:"France"},
    {value:"GF",label:"French Guiana"},
    {value:"PF",label:"French Polynesia"},
    {value:"TF",label:"French Southern Territories"},
    {value:"GA",label:"Gabon"},
    {value:"GM",label:"Gambia"},
    {value:"GE",label:"Georgia"},
    {value:"DE",label:"Germany"},
    {value:"GH",label:"Ghana"},
    {value:"GI",label:"Gibraltar"},
    {value:"GR",label:"Greece"},
    {value:"GL",label:"Greenland"},
    {value:"GD",label:"Grenada"},
    {value:"GP",label:"Guadeloupe"},
    {value:"GU",label:"Guam"},
    {value:"GT",label:"Guatemala"},
    {value:"GG",label:"Guernsey"},
    {value:"GN",label:"Guinea"},
    {value:"GW",label:"Guinea-Bissau"},
    {value:"GY",label:"Guyana"},
    {value:"HT",label:"Haiti"},
    {value:"HM",label:"Heard Island and McDonald Islands"},
    {value:"VA",label:"Holy See"},
    {value:"HN",label:"Honduras"},
    {value:"HK",label:"Hong Kong"},
    {value:"HU",label:"Hungary"},
    {value:"IS",label:"Iceland"},
    {value:"IN",label:"India"},
    {value:"ID",label:"Indonesia"},
    {value:"IR",label:"Iran"},
    {value:"IQ",label:"Iraq"},
    {value:"IE",label:"Ireland"},
    {value:"IM",label:"Isle of Man"},
    {value:"IT",label:"Italy"},
    {value:"JM",label:"Jamaica"},
    {value:"JP",label:"Japan"},
    {value:"JE",label:"Jersey"},
    {value:"JO",label:"Jordan"},
    {value:"KZ",label:"Kazakhstan"},
    {value:"KE",label:"Kenya"},
    {value:"KI",label:"Kiribati"},
    {value:"KP",label:"Korea (Democratic People's Republic of)"},
    {value:"KR",label:"Korea (Republic of)"},
    {value:"KW",label:"Kuwait"},
    {value:"KG",label:"Kyrgyzstan"},
    {value:"LA",label:"Lao People's Democratic Republic"},
    {value:"LV",label:"Latvia"},
    {value:"LB",label:"Lebanon"},
    {value:"LS",label:"Lesotho"},
    {value:"LR",label:"Liberia"},
    {value:"LY",label:"Libya"},
    {value:"LI",label:"Liechtenstein"},
    {value:"LT",label:"Lithuania"},
    {value:"LU",label:"Luxembourg"},
    {value:"MO",label:"Macao"},
    {value:"MK",label:"Macedonia (the former Yugoslav Republic of)"},
    {value:"MG",label:"Madagascar"},
    {value:"MW",label:"Malawi"},
    {value:"MY",label:"Malaysia"},
    {value:"MV",label:"Maldives"},
    {value:"ML",label:"Mali"},
    {value:"MT",label:"Malta"},
    {value:"MH",label:"Marshall Islands"},
    {value:"MQ",label:"Martinique"},
    {value:"MR",label:"Mauritania"},
    {value:"MU",label:"Mauritius"},
    {value:"YT",label:"Mayotte"},
    {value:"MX",label:"Mexico"},
    {value:"FM",label:"Micronesia (Federated States of)"},
    {value:"MD",label:"Moldova (Republic of)"},
    {value:"MC",label:"Monaco"},
    {value:"MN",label:"Mongolia"},
    {value:"ME",label:"Montenegro"},
    {value:"MS",label:"Montserrat"},
    {value:"MA",label:"Morocco"},
    {value:"MZ",label:"Mozambique"},
    {value:"MM",label:"Myanmar"},
    {value:"NA",label:"Namibia"},
    {value:"NR",label:"Nauru"},
    {value:"NP",label:"Nepal"},
    {value:"NL",label:"Netherlands"},
    {value:"NC",label:"New Caledonia"},
    {value:"NZ",label:"New Zealand"},
    {value:"NI",label:"Nicaragua"},
    {value:"NE",label:"Niger"},
    {value:"NG",label:"Nigeria"},
    {value:"NU",label:"Niue"},
    {value:"NF",label:"Norfolk Island"},
    {value:"MP",label:"Northern Mariana Islands"},
    {value:"NO",label:"Norway"},
    {value:"OM",label:"Oman"},
    {value:"PK",label:"Pakistan"},
    {value:"PW",label:"Palau"},
    {value:"PS",label:"Palestine, State of"},
    {value:"PA",label:"Panama"},
    {value:"PG",label:"Papua New Guinea"},
    {value:"PY",label:"Paraguay"},
    {value:"PE",label:"Peru"},
    {value:"PH",label:"Philippines"},
    {value:"PN",label:"Pitcairn"},
    {value:"PL",label:"Poland"},
    {value:"PT",label:"Portugal"},
    {value:"PR",label:"Puerto Rico"},
    {value:"QA",label:"Qatar"},
    {value:"RE",label:"Réunion"},
    {value:"RO",label:"Romania"},
    {value:"RU",label:"Russian Federation"},
    {value:"RW",label:"Rwanda"},
    {value:"BL",label:"Saint Barthelemy"},
    {value:"SH",label:"Saint Helena, Ascension and Tristan da Cunha"},
    {value:"KN",label:"Saint Kitts and Nevis"},
    {value:"LC",label:"Saint Lucia"},
    {value:"MF",label:"Saint Martin (French part)"},
    {value:"PM",label:"Saint Pierre and Miquelon"},
    {value:"VC",label:"Saint Vincent and the Grenadines"},
    {value:"WS",label:"Samoa"},
    {value:"SM",label:"San Marino"},
    {value:"ST",label:"Sao Tome and Principe"},
    {value:"SA",label:"Saudi Arabia"},
    {value:"SN",label:"Senegal"},
    {value:"RS",label:"Serbia"},
    {value:"SC",label:"Seychelles"},
    {value:"SL",label:"Sierra Leone"},
    {value:"SG",label:"Singapore"},
    {value:"SX",label:"Sint Maarten (Dutch part)"},
    {value:"SK",label:"Slovakia"},
    {value:"SI",label:"Slovenia"},
    {value:"SB",label:"Solomon Islands"},
    {value:"SO",label:"Somalia"},
    {value:"ZA",label:"South Africa"},
    {value:"GS",label:"South Georgia and the South Sandwich Islands"},
    {value:"SS",label:"South Sudan"},
    {value:"ES",label:"Spain"},
    {value:"LK",label:"Sri Lanka"},
    {value:"SD",label:"Sudan"},
    {value:"SR",label:"Suriname"},
    {value:"SJ",label:"Svalbard and Jan Mayen"},
    {value:"SZ",label:"Swaziland"},
    {value:"SE",label:"Sweden"},
    {value:"CH",label:"Switzerland"},
    {value:"SY",label:"Syrian Arab Republic"},
    {value:"TW",label:"Taiwan, Province of China[a]"},
    {value:"TJ",label:"Tajikistan"},
    {value:"TZ",label:"Tanzania, United Republic of"},
    {value:"TH",label:"Thailand"},
    {value:"TL",label:"Timor-Leste"},
    {value:"TG",label:"Togo"},
    {value:"TK",label:"Tokelau"},
    {value:"TO",label:"Tonga"},
    {value:"TT",label:"Trinidad and Tobago"},
    {value:"TN",label:"Tunisia"},
    {value:"TR",label:"Turkey"},
    {value:"TM",label:"Turkmenistan"},
    {value:"TC",label:"Turks and Caicos Islands"},
    {value:"TV",label:"Tuvalu"},
    {value:"UG",label:"Uganda"},
    {value:"UA",label:"Ukraine"},
    {value:"AE",label:"United Arab Emirates"},
    {value:"GB",label:"United Kingdom of Great Britain and Northern Ireland"},
    {value:"US",label:"United States of America"},
    {value:"UM",label:"United States Minor Outlying Islands"},
    {value:"UY",label:"Uruguay"},
    {value:"UZ",label:"Uzbekistan"},
    {value:"VU",label:"Vanuatu"},
    {value:"VE",label:"Venezuela (Bolivarian Republic of)"},
    {value:"VN",label:"Viet Nam"},
    {value:"VG",label:"Virgin Islands (British)"},
    {value:"VI",label:"Virgin Islands (U.S.)"},
    {value:"WF",label:"Wallis and Futuna"},
    {value:"EH",label:"Western Sahara"},
    {value:"YE",label:"Yemen"},
    {value:"ZM",label:"Zambia"},
    {value:"ZW",label:"Zimbabwe"}
];